### ISSUE TITLE
loompy.connect cannot access file

### ISSUE THREAD

**Issue by simone-codeluppi** [linnarsson-lab/loompy#102]
Hi
I generated a set of loom files and i will need to read them and add data. However I get an os error in accessing the file. If i use h5py directly I can load the file. The files generated pass the validation (correct loom format):

``` python
OSError                                   Traceback (most recent call last)
<ipython-input-16-0260eabf588b> in <module>
----> 1 d = loompy.connect(str(comp_fpath))

/fish/simone_processing/Code/loompy/loompy/loompy.py in connect(filename, mode, validate, spec_version)
   1308                 Note: if validation is requested, an exception is raised if validation fails.
   1309         """
-> 1310         return LoomConnection(filename, mode, validate=validate, spec_version=spec_version)

/fish/simone_processing/Code/loompy/loompy/loompy.py in __init__(self, filename, mode, validate, spec_version)
     87                                 raise ValueError("\n".join(lv.errors) + f"\n{filename} does not appead to be a valid Loom file according to Loom spec version '{spec_version}'")
     88 
---> 89                 self._file = h5py.File(filename, mode)
     90                 self._closed = False
     91                 if "matrix" in self._file:

/fish/simone_processing/anaconda3/envs/htc_env/lib/python3.7/site-packages/h5py/_hl/files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, rdcc_nslots, rdcc_nbytes, rdcc_w0, track_order, **kwds)
    392                 fid = make_fid(name, mode, userblock_size,
    393                                fapl, fcpl=make_fcpl(track_order=track_order),
--> 394                                swmr=swmr)
    395 
    396             if swmr_support:

/fish/simone_processing/anaconda3/envs/htc_env/lib/python3.7/site-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    170         fid = h5f.open(name, flags, fapl=fapl)
    171     elif mode == 'r+':
--> 172         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
    173     elif mode in ['w-', 'x']:
    174         fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')
```

**Comment by slinnarsson** [comment]
You probably are trying to open the same file from multiple processes. You need to open as read only (”r” mode) in order for that to work!

**Comment by slinnarsson** [comment]
If you need to write to the file, you will have to catch the error and try again, in a loop, until it works. That will ensure only one process has the file open at any given time.

**Comment by simone-codeluppi** [comment]
Interestingly it gets fixed if I pass mode = 'r' suggesting that may be a process issue even thought I am not opening/closing the same file. If i want to open the file as `mode='r+'` and catch the `OSError`  using a loop, it get stuck in an infinity loop even if I add a delay hinting that may not be a process issue.
The interesting thing is that i run the exactly the same code before and didn't have any issue.....As tmp solution I can read all the files as 'r' and create a new file to write the result, i just wanted to be more efficient and just add data to the same file.

**Comment by slinnarsson** [comment]
Ok that’s strange. Might be a filesystem issue? Some filesystems can have weird behaviour for locking files. 

(Also, just in case: make sure you always use the ”with loompy.connect()...” idiom, so that your files get closed properly no matter what happens. )

**Comment by simone-codeluppi** [comment]
perfect. thanks
