### ISSUE TITLE
slicing loom file 

### ISSUE THREAD

**Issue by hmassalha** [linnarsson-lab/loompy#103]
Hi all, 
I am very new to Python and the loom format. Sorry for the basic question. 
I am looking for a way to slice my loom file based on column/row attributes and retrieve an updated loom file.  For example, slicing the data based on a boolean cellIDs, where the result will be a sliced data in all layers of the original loom file. Basically filtering the data across all layers. 
Any help with this is much appreciated.

Thanks, HM

**Comment by slinnarsson** [comment]
Use the view attribute, and slice it:

```python
with loompy.connect(filename) as ds:
    view = ds.view[:, ds.ca.NCells > 100]
```

This will slice through all the layers, graphs and attributes. You can then save the view using `loompy.create(outname, view.layers, view.ra, view.ca)`

**Comment by hmassalha** [comment]
Great, Thanks for the quick reply, HM

**Comment by hmassalha** [comment]
Hi again, 

```
boolvec=np.array([elem in seurat_cells for elem in loom_cells])
with loompy.connect(dirr+"human5_loom.loom") as ds:
    ds.view[:,ds.ca.CellID[boolvec]]

```

I get `arrays used as indices must be of integer (or boolean) type`!! I played with it a little bit with no success. Sorry for the basic question I have Matlab background.

**Comment by slinnarsson** [comment]
Well, is `boolvec` an array of bools or integers? I'm not sure what the expression `[elem in seurat_cells for elem in loom_cells]` will do (depends on what the input is), but you can check the type of `boolvec` by doing `print(boolvec.dtype)`. 

Make sure that `boolvec` is really a boolean array with `True` for the cells you want, or an integer array giving the indices of those cells.

**Comment by hmassalha** [comment]
Thanks again for the quick reply. 

`boolvec` is:
```
boolvec
array([False, False, False, ...,  True, False, False])
```
and the type is:
```
print(boolvec.dtype)
bool
```

**Comment by slinnarsson** [comment]
Oh, I see the error now. You should just use boolvec directly in the slice. ds.ca.CellID[boolvec] returns an array of strings (the cell IDs).

**Comment by hmassalha** [comment]
Thanks, the idea is to slice the entire loom object. How would you replace the expression ` ds.view[:,ds.ca.CellID[boolvec]]` in order to avoid the error message. 
Doing `ds.ca.CellID[boolvec]` will give the masked cellID. I want to mask the entire loom object. 

Thanks, HM

**Comment by slinnarsson** [comment]
To slice an array, you musty provide a bool array or an integer array (of indices). You're using `ds.ca.CellID[boolvec]`, which is an array of strings. Just use `boolvec` itself instead:

```python
boolvec = np.array([elem in seurat_cells for elem in loom_cells])
with loompy.connect(dirr + "human5_loom.loom") as ds:
    view = ds.view[:, boolvec]
```

Or a bit more succinctly:

```python
with loompy.connect(dirr + "human5_loom.loom") as ds:
    view = ds.view[:, np.isin(ds.ca.CellID, seurat_cells)]
```

**Comment by hmassalha** [comment]
WORKING... Thanks a lot!
I prefer to use the first option as I am doing string manipulation on the CellIDs and retrieve a logical vector. 

Thanks again, HM
