### ISSUE TITLE
importing column attributes in order

### ISSUE THREAD

**Issue by phbrito** [linnarsson-lab/loompy#107]
I am using loompy to import cell embeddings from Seurat to velocyto. 
The problem is that the order of cells in Seurat object is not the same as in the loom file that I created with velocyto run10x and so the embeddings are attributed to the wrong cells.

My code:
ds= loompy.connect("/data/105H/velocyto/105H.loom")
ds.ca.TSNE1=tSNE1
ds.ca.TSNE2=tSNE2
ds.ca.ClusterName=clusters
ds.close()

#note: tSNE1, tSNE2 and clusters are python lists made from a file that was exported from Seurat.

My question is if there a way to add column attributes using a key element such as CellID just to make sure that we add the embeddings to the write cell.
Same reasoning as when we use "key="Accession" in: 
loompy.combine(files ,"105H.All.loom" , key="Accession")

Thanks!!

**Comment by slinnarsson** [comment]
Hi,

No sorry there's no such feature. You can reorder your attributes (`tSNE1` etc.) using the ordering vector obtained by `np.argsort(my_cell_ids)[np.argsort(np.argsort(cell_ids_in_loom))]`, e.g. like so:  

```python
# CellIDs and attribute values in your arbitrary order
my_cell_ids = np.array([2, 3, 1, 4])
# Using letters here to make it easy to compare with result
my_tsne = np.array(["a", "b", "c", "d"])  

# Use a with-block to ensure the file closes automatically
with  loompy.connect("/data/105H/velocyto/105H.loom") as ds:
    cell_ids_in_loom = ds.ca.CellID  # e.g. np.array([4, 2, 1, 3])
    ordering = np.argsort(my_cell_ids)[np.argsort(np.argsort(cell_ids_in_loom))]
    ds.ca.MyTSNE = my_attributes[ordering]
    print(ds.ca.MyTSNE)
```

which yields

```python
['d' 'a' 'c' 'b']
```

But please check your results in case I made a mistake.
