### ISSUE TITLE
Question: spec compliance tests

### ISSUE THREAD

**Issue by romgrk** [linnarsson-lab/loompy#109]
Hey,

I'm developing a module to create loom file with Node.js, is there some tool I could use to validate that the created files respect the spec?

Thanks

Reference: https://github.com/romgrk/node-loompy

**Comment by slinnarsson** [comment]
Hi

That's great - thanks for contributing! Yes, if you use the Python API, you can ask for validation against the spec (in fact, that's the default). For example:

```python
with loompy.connect(filename, validate=True) as ds:
    print("File is ok")
```

If the file fails to validate, an exception is thrown.

**Comment by romgrk** [comment]
Awesome, thanks! If you'd like to mention this alternative for nodejs users on your page it could be nice, I couldn't find any way to use loom file other than the Python API. The module is still a bit experimental though, and the API limited to `loompy.create`.

**Comment by slinnarsson** [comment]
Of course - I’ll put a link to your project on loompy.org along with the 3.0 release, which I hope to have out by end of Sep.

**Comment by romgrk** [comment]
Got it, thanks! Validation works :)
