### ISSUE TITLE
ValueError: This validator can only validate against Loom specs '2.0.1' or 'old'

### ISSUE THREAD

**Issue by darmen04** [linnarsson-lab/loompy#117]
Hello,
I am currently trying to run loompy directly using fastq files from your tutorial. However after running loompy fromfq I receive the following using loompy v3.0.3: 

Traceback (most recent call last):
  File "/home2/s425140/.conda/envs/py36/bin/loompy", line 10, in <module>
    sys.exit(cli())
  File "/home2/s425140/.conda/envs/py36/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home2/s425140/.conda/envs/py36/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home2/s425140/.conda/envs/py36/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home2/s425140/.conda/envs/py36/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home2/s425140/.conda/envs/py36/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home2/s425140/.conda/envs/py36/lib/python3.6/site-packages/loompy/commands.py", line 34, in fromfq
    create_from_fastq(loomfile, sampleid, list(fastqs), indexdir, metadatafile, threads)
  File "/home2/s425140/.conda/envs/py36/lib/python3.6/site-packages/loompy/bus_file.py", line 456, in create_from_fastq
    with connect(out_file) as ds:
  File "/home2/s425140/.conda/envs/py36/lib/python3.6/site-packages/loompy/loompy.py", line 1389, in connect
    return LoomConnection(filename, mode, validate=validate, spec_version=spec_version)
  File "/home2/s425140/.conda/envs/py36/lib/python3.6/site-packages/loompy/loompy.py", line 80, in __init__
    lv = loompy.LoomValidator(version=spec_version)
  File "/home2/s425140/.conda/envs/py36/lib/python3.6/site-packages/loompy/loom_validator.py", line 19, in __init__
    raise ValueError("This validator can only validate against Loom specs '2.0.1' or 'old'")
ValueError: This validator can only validate against Loom specs '2.0.1' or 'old'

Do you have any suggestions as to how I may get around this? Thank you!

**Comment by ivirshup** [comment]
I haven't had time to dig into it yet, but we're also seeing this in `anndata`s `read_loom` and `write_loom` (https://github.com/theislab/anndata/issues/232).

Here's a little example of what triggers the error:

```python
from scipy import sparse
import numpy as np

import loompy  # Version 3.0.3

layers = {"": sparse.random(1000, 1000, format="csr")}
row_attrs = {"ids": np.arange(1000)}
col_attrs = {"ids": np.arange(1000)}

loompy.create("tmp.loom", layers, row_attrs, col_attrs)
connection = loompy.connect("tmp.loom", "r")
```

<details>
<summary> Traceback </summary>

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-0cb21647e2c2> in <module>
      9 
     10 loompy.create("tmp.loom", layers, row_attrs, col_attrs)
---> 11 connection = loompy.connect("tmp.loom", "r")

/usr/local/lib/python3.7/site-packages/loompy/loompy.py in connect(filename, mode, validate, spec_version)
   1387                 Note: if validation is requested, an exception is raised if validation fails.
   1388 	"""
-> 1389         return LoomConnection(filename, mode, validate=validate, spec_version=spec_version)

/usr/local/lib/python3.7/site-packages/loompy/loompy.py in __init__(self, filename, mode, validate, spec_version)
     78                 # Validate the file
     79                 if validate:
---> 80                         lv = loompy.LoomValidator(version=spec_version)
     81                         if not lv.validate(filename):
     82                                 raise ValueError("\n".join(lv.errors) + f"\n{filename} does not appead to be a valid Loom file according to Loom spec version '{spec_version}'")

/usr/local/lib/python3.7/site-packages/loompy/loom_validator.py in __init__(self, version)
     17                 self.version = version  #: Version of the spec to validate against
     18                 if version != "2.0.1" and version != 'old':
---> 19                         raise ValueError("This validator can only validate against Loom specs '2.0.1' or 'old'")
     20                 self.errors: List[str] = []  #: Errors found during validation
     21                 self.warnings: List[str] = []  #: Warnings triggered during validation

ValueError: This validator can only validate against Loom specs '2.0.1' or 'old'
```

</details>

**Comment by slinnarsson** [comment]
Sorry, my mistake. I was running the test script on a newer version. I will merge the 3.0.0 validator and push a new version later today.

**Comment by slinnarsson** [comment]
Fixed in 3.0.4, and pushed to pypi.

**Comment by slinnarsson** [comment]
Fixed a few regressions when opening old loom files using the 3.0.0 validator. Pushed a new release as v3.0.5

**Comment by ivirshup** [comment]
Works for us now, thanks!
