### ISSUE TITLE
Question over compatibilities with Loom v3

### ISSUE THREAD

**Issue by VincentGardeux** [linnarsson-lab/loompy#118]
Hello,

I'm one of the developers of the ASAP portal (asap.epfl.ch / asap-beta.epfl.ch)
Maybe you remembered, but I was also the one asking about the variable String/UTF-8 format, and I'm super enjoyed to see it implemented in Loom v3, thanks a lot for this!

We implemented the Loom format in the new beta version of ASAP, and are also collaborating with Stein's group for cross-compatibilities with Scope (feat. Fly Cell Atlas)

I'm now contemplating the Loomv3 format, and try to update ASAP's parsing step so it can directly generate files compliant with v3 format.
However I don't understand why but my Loom files are rejected by the Loompy parser with the following errors:

```
Row attribute 'Accession' dtype object is not allowed
Row attribute 'Gene' dtype object is not allowed
Row attribute '_Biotypes' dtype object is not allowed
Row attribute '_Chromosomes' dtype object is not allowed
Column attribute 'CellID' dtype object is not allowed
For help, see http://linnarssonlab.org/loompy/format/
/home/gardeux/output.loom does not appead to be a valid Loom file according to Loom spec version 'v3.0.0'
```

You can download the incriminated Loom file [here](http://gardeux-vincent.eu/output.loom)

Apparently there is a String format issue, but HDFView tells me that the Strings are indeed variable + UTF-8 encoded?

Thanks for the great work, and for the future answer!

Cheers

Vincent Gardeux

**Comment by slinnarsson** [comment]
Hi

Are you on loompy 3.0.6? There was a brief issue with the validator in 3.0.4, which I fixed. If that’s not it, I’ll check your file once I get back to the office on Monday (currently travelling)!

**Comment by VincentGardeux** [comment]
Hi,

Yes I have loompy 3.0.6 installed.
But the version in the Loom file is set to "v3.0.0", is this correct?

Cheers

**Comment by slinnarsson** [comment]
Ah, I see the error now - the LOOM_SPEC_VERSION should be "3.0.0" (without the leading "v")! I modified your file to have the correct string, and it now seems to work.

Sorry about that. I fixed the file format specification in the docs now, to the correct version string.

The file format version will stay "3.0.0" until I have to make a change to the spec (hopefully not until 4.0.0), whereas the loompy library version changes for every release.

**Comment by VincentGardeux** [comment]
Yep, works like a charm!
Thanks again

**Comment by liushang17** [comment]
Hi, I have the same error. How to change it. Thanks very much.

**Comment by cadyyuheng** [comment]
Hi @slinnarsson, I encountered the same issue. Could you please specify which file contains LOOM_SPEC_VERSION and how to modify it? Thank you in advance!

**Comment by slinnarsson** [comment]
It’s an attribute of the Loom file itself. You can use [h5py](http://www.h5py.org/) to change it.
