### ISSUE TITLE
fromfq: specify a tmp folder?

### ISSUE THREAD

**Issue by sonejilab** [linnarsson-lab/loompy#119]
Hi,
I tried running loompy fromfq on my local workstation, but by default it uses /tmp which on my system borked the run because it ran out of space.

I couldn't see an option to specify a location for temp/output files, so would it be possible to add one that is passed to kallisto during alignment? 

Many thanks!
Shamit

**Comment by slinnarsson** [comment]
Sorry about that. I’m using the standard Python tempdir API. According to this: https://stackoverflow.com/questions/18280245/where-does-python-tempfile-writes-its-files you can set the TMPDIR environment variable to direct temp dirs to another location.

**Comment by sonejilab** [comment]
Ok great I'll give this a shot, thanks for getting back to me. Would it be useful however to have an option for people like me who are more R based than Python? Apart from this small glitch fromfq is working really well for me.
