### ISSUE TITLE
help with loom file manipulation

### ISSUE THREAD

**Issue by gujjas** [linnarsson-lab/loompy#124]
Hi,
I am writing to get some help with adding column attributes to a loom file. I have precomputed umap co-ordinates, and color assignments as flat files for a **subset** of cell ids, which I'd like to add to the loom file. Can you please help on how to subset and then assign new data to the loom file.
Ex: cell.color file
cell.ID	color
AAACCTGAGAAGGACA	purple4
AAACCTGAGGATTCGG	orangered
AAACCTGCATGGGAAC	orangered
AAACCTGGTGATAAAC	steelblue3
...
cell.embedding
cell.ID	UMAP.1	UMAP.2
AAACCTGAGAAGGACA	-0.224256387	-5.567305085
AAACCTGAGGATTCGG	-3.024903685	-5.885387304
AAACCTGCATGGGAAC	-1.691906004	-6.446423877
AAACCTGGTGATAAAC	-4.984767827	-6.937280836
...

The cell ids in the loom file are:
['R18037623-96-SI-GA-A3_Aligned_G8L8X:AAAGATGTCGGCTTGG'
 'R18037623-96-SI-GA-A3_Aligned_G8L8X:AAAGTAGTCTGCGTAA'
 'R18037623-96-SI-GA-A3_Aligned_G8L8X:AAATGCCGTACCAGTT' ...
 'R18037623-96-SI-GA-A3_Aligned_G8L8X:TTGGAACAGGCAAAGA'
 'R18037623-96-SI-GA-A3_Aligned_G8L8X:TTTGCGCCATTCCTGC'
 'R18037623-96-SI-GA-A3_Aligned_G8L8X:TTGGCAAGTAAAGTCA']
Thanks for helping.

**Comment by slinnarsson** [comment]
Hi

The trick is to use numpy fancy indexing to assign to a subset of a full array. Something like 

```python
color_ids = # cell ids for those cells that have colors
color = # numpy array of values for a subset of columns
color_all = np.zeros(ds.shape[1], dtype=object)
indices = [np.where(ds.ca.CellID == cid)[0] for cid in color_ids]
color_all[indices] = color
ds.ca.Color = color_all
```

I didn't test it so you may have to fix some errors (maybe there should be an extra [0] after the `np.where(...)` expression)

**Comment by gujjas** [comment]
Hi Sten,

Thank you so much for the reply. I really appreciate it. I am trying to get some help trying to understand why the arrows are not consistent between the figures generated from R and python:

https://github.com/velocyto-team/velocyto-notebooks/issues/19

I am not sure if this should be posted under R or python issues – it would be great if you could provide some feedback or point me to the right person who could help with this.

Thanks again.
Sharvari


Sharvari Gujja
Assistant Director, Advanced Artificial
Intelligence Research Laboratory
––
[cid:image001.png@01D5FB87.BBD9D670]
Leading Genomics
C: 617.444.9040
