### ISSUE TITLE
Using latest HDF5 libver?

### ISSUE THREAD

**Issue by JobLeonard** [linnarsson-lab/loompy#13]
Something to consider:

> HDF5 has been evolving for many years now. By default, the library will write objects in the most compatible fashion possible, so that older versions will still be able to read files generated by modern programs. **However, there can be performance advantages if you are willing to forgo a certain level of backwards compatibility.** By using the “libver” option to File, you can specify the minimum and maximum sophistication of these structures:
> 
> ```python
> >>> f = h5py.File('name.hdf5', libver='earliest') # most compatible
> >>> f = h5py.File('name.hdf5', libver='latest')   # most modern
> ```
> 
> Here “latest” means that HDF5 will always use the newest version of these structures without particular concern for backwards compatibility. The “earliest” option means that HDF5 will make a best effort to be backwards compatible.
>
> The default is “earliest”.

http://docs.h5py.org/en/latest/high/file.html#version-bounding

I'm more than slightly annoyed by the vagueness of "a certain level of  backwards compatibility", but ok. Anyway, I'm bringing this up because according to [these slides about h5py usage by the NERSC](https://www.nersc.gov/assets/Uploads/H5py-2017-Feb23.pdf), using `libver='latest'` results in 2.25x better performance for them. Could end up quite significant if the loom files increase in size in the future.

(also, this might also be part of the reason that increasing the chunk cache did not help last time we tried it)

**Comment by slinnarsson** [comment]
This will require confirmed support in other languages for the most recent HDF5 version. We want at least R, MATLAB, Mathematica and Julia (and C/C++, but that should be automatic) to work out of the box with no fuss.

`libver='latest'` sounds very vague and how will we even know what that means (on any specific user's computer)?

Let's not go there now, but keep in mind for future.
