### ISSUE TITLE
Raw Data from Seurat Loom File

### ISSUE THREAD

**Issue by iSinedeus** [linnarsson-lab/loompy#130]
Hello,

I am trying to use a seurat object that contains multiple samples of scRNA seq data which I have qced using the seurat workflow. I am able to create a loom file and load it into python but by default there is no adata.raw set when I load this file in. From the scanpy workflow I noticed this variable is normally set using adata = adata.raw prior to performing scaling of the data. I was wondering if I export a seurat object with scaled data if it’s still possible to obtain this raw data from that file or if I need to try to export that object without the scaled data being present?  I have run integration through scanpy by simply setting adata = adata.raw and following the steps in their tutorial but I am seeing significant batch effect present. I’m sorry if this may not be the correct forum for this question but it seems like there isn’t a single place to get an answer to my questions so I appreciate any feedback anyone here is able to offer.

Thank you

**Comment by mschilli87** [comment]
also see https://github.com/mojaveazure/loomR/issues/62

**Comment by slinnarsson** [comment]
Hi - this seems like a question for the seurat or scanpy developers
