### ISSUE TITLE
create from fastq_genome index for smartseq2 data

### ISSUE THREAD

**Issue by qiqing-li** [linnarsson-lab/loompy#133]
The current [documentation](http://linnarssonlab.org/loompy/kallisto/index.html) of create loom files from fastq seems to only be compatible with 10x data. Is it possible to build genome index from smartseq2 data? Or how to use loompy to generate loom files for smartseq2 data? Thanks!

**Comment by slinnarsson** [comment]
Hi - no, sorry we have no plans to support additional data sources. Have a look at kallisto or STARsolo, which might be able to do what you need.
