### ISSUE TITLE
Restrictions on attribute names?

### ISSUE THREAD

**Issue by JobLeonard** [linnarsson-lab/loompy#14]
I remember that we started with a limitation to alphanumeric characters and underscores. Has this restriction been lifted? I don't see it anywhere in the docs any more, and there are a few attribute names in some of our loom files that include spaces, quotes and such.

This would affect `loom-viewer` code, since it assumes these restrictions still are in place.

**Comment by slinnarsson** [comment]
Closed in favor of #19
