### ISSUE TITLE
Support creation from sparse matrices

### ISSUE THREAD

**Issue by vals** [linnarsson-lab/loompy#16]
If I make my expression matrix dense I run out of RAM and Python crashes.

It would be good if loom files could be created straight from COO sparse matrices.

**Comment by slinnarsson** [comment]
It already does. Just supply a sparse matrix to the create() method, and it should work!

**Comment by slinnarsson** [comment]
FYI, the opposite method is called sparse(). It returns a sparse matrix without loadibg the dense representation in memory.

**Comment by vals** [comment]
Hi Sten,

When I ran the `create` function on some real data, I got the following error message

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-2efabda85022> in <module>()
      1 loompy.create('/Users/vale/Desktop/test.loom', m_coo,
      2               {'gid': np.arange(m_coo.shape[0])},
----> 3               {'cid': np.arange(m_coo.shape[1])}, )

~/anaconda/lib/python3.6/site-packages/loompy/loompy.py in create(filename, matrix, row_attrs, col_attrs, file_attrs, chunks, chunk_cache, dtype, compression_opts)
   1019 
   1020         if scipy.sparse.issparse(matrix):
-> 1021                 return _create_sparse(filename, matrix, row_attrs, col_attrs, file_attrs, chunks, chunk_cache, dtype, compression_opts)
   1022 
   1023         # Create the file (empty).

~/anaconda/lib/python3.6/site-packages/loompy/loompy.py in _create_sparse(filename, matrix, row_attrs, col_attrs, file_attrs, chunks, chunk_cache, dtype, compression_opts)
    982                 if ds is None:
    983                         logging.info("Creating")
--> 984                         ds = create(filename, matrix[:, ix:ix + window].toarray(), row_attrs, ca, file_attrs, chunks, chunk_cache, dtype, compression_opts)
    985                 else:
    986                         logging.info("Adding columns")

~/anaconda/lib/python3.6/site-packages/loompy/loompy.py in create(filename, matrix, row_attrs, col_attrs, file_attrs, chunks, chunk_cache, dtype, compression_opts)
   1030 
   1031         ds = connect(filename)
-> 1032         ds.set_layer("", matrix, chunks, chunk_cache, dtype, compression_opts)
   1033 
   1034         for key, vals in row_attrs.items():

~/anaconda/lib/python3.6/site-packages/loompy/loompy.py in set_layer(self, name, matrix, chunks, chunk_cache, dtype, compression_opts)
    343                                 compression="gzip",
    344                                 shuffle=False,
--> 345                                 compression_opts=compression_opts
    346 			)
    347 

~/anaconda/lib/python3.6/site-packages/h5py/_hl/group.py in create_dataset(self, name, shape, dtype, data, **kwds)
    103         """
    104         with phil:
--> 105             dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
    106             dset = dataset.Dataset(dsid)
    107             if name is not None:

~/anaconda/lib/python3.6/site-packages/h5py/_hl/dataset.py in make_new_dset(parent, shape, dtype, data, chunks, compression, shuffle, fletcher32, maxshape, compression_opts, fillvalue, scaleoffset, track_times)
     74     tmp_shape = maxshape if maxshape is not None else shape
     75     # Validate chunk shape
---> 76     if isinstance(chunks, tuple) and (-numpy.array([ i>=j for i,j in zip(tmp_shape,chunks) if i is not None])).any():
     77         errmsg = "Chunk shape must not be greater than data shape in any dimension. "\
     78                  "{} is not compatible with {}".format(chunks, shape)

TypeError: The numpy boolean negative, the `-` operator, is not supported, use the `~` operator or the logical_not function instead.
```

When I tried to make a minimal example, I got a different error however:

```
G = 10000
C = 100
S = sparse.eye(C, G).tocoo()

loompy.create('~/Desktop/test.loom', S,
              {'g_id': np.arange(G)},
              {'c_id': np.arange(C)}, )
```

Which gives

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-25-52cb84c445d9> in <module>()
      1 loompy.create('~/Desktop/test.loom', S,
      2               {'g_id': np.arange(G)},
----> 3               {'c_id': np.arange(C)}, )

~/anaconda/lib/python3.6/site-packages/loompy/loompy.py in create(filename, matrix, row_attrs, col_attrs, file_attrs, chunks, chunk_cache, dtype, compression_opts)
   1019 
   1020         if scipy.sparse.issparse(matrix):
-> 1021                 return _create_sparse(filename, matrix, row_attrs, col_attrs, file_attrs, chunks, chunk_cache, dtype, compression_opts)
   1022 
   1023         # Create the file (empty).

~/anaconda/lib/python3.6/site-packages/loompy/loompy.py in _create_sparse(filename, matrix, row_attrs, col_attrs, file_attrs, chunks, chunk_cache, dtype, compression_opts)
    982                 if ds is None:
    983                         logging.info("Creating")
--> 984                         ds = create(filename, matrix[:, ix:ix + window].toarray(), row_attrs, ca, file_attrs, chunks, chunk_cache, dtype, compression_opts)
    985                 else:
    986                         logging.info("Adding columns")

~/anaconda/lib/python3.6/site-packages/loompy/loompy.py in create(filename, matrix, row_attrs, col_attrs, file_attrs, chunks, chunk_cache, dtype, compression_opts)
   1022 
   1023         # Create the file (empty).
-> 1024         f = h5py.File(name=filename, mode='w')
   1025         f.create_group('/layers')
   1026         f.create_group('/row_attrs')

~/anaconda/lib/python3.6/site-packages/h5py/_hl/files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, **kwds)
    270 
    271                 fapl = make_fapl(driver, libver, **kwds)
--> 272                 fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
    273 
    274                 if swmr_support:

~/anaconda/lib/python3.6/site-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
     96         fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
     97     elif mode == 'w':
---> 98         fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
     99     elif mode == 'a':
    100         # Open in append mode (read/write).

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/Users/ilan/minonda/conda-bld/h5py_1482533836832/work/h5py/_objects.c:2856)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/Users/ilan/minonda/conda-bld/h5py_1482533836832/work/h5py/_objects.c:2814)()

h5py/h5f.pyx in h5py.h5f.create (/Users/ilan/minonda/conda-bld/h5py_1482533836832/work/h5py/h5f.c:2269)()

OSError: Unable to create file (Unable to open file: name = '~/desktop/test.loom', errno = 2, error message = 'no such file or directory', flags = 13, o_flags = 602)
```

**Comment by slinnarsson** [comment]
Both seem to be bugs in h5py, but I also found a bug in loompy that contributes.

H5py doesn’t seem to like the tilde character in pathnames. Spell it out (”/Users/usename/Desktop/...”) and it works. But you’ll hit another bug which I have now fixed. I will push thd commit tonight when I get internet access.

Sten

--
Sten Linnarsson, PhD
Professor of Molecular Systems Biology
Karolinska Institutet
Unit of Molecular Neurobiology
Department of Medical Biochemistry and Biophysics
Scheeles väg 1, 171 77 Stockholm, Sweden<x-apple-data-detectors://1/0>
+46 8 52 48 75 77<tel:+46%208%2052%2048%2075%2077> (office)
+46 70 399 32 06<tel:+46%2070%20399%2032%2006> (mobile)


13 nov. 2017 kl. 04:20 skrev Valentine Svensson <notifications@github.com<mailto:notifications@github.com>>:


Hi Sten,

When I ran the create function on some real data, I got the following error message

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-2efabda85022> in <module>()
      1 loompy.create('/Users/vale/Desktop/test.loom', m_coo,
      2               {'gid': np.arange(m_coo.shape[0])},
----> 3               {'cid': np.arange(m_coo.shape[1])}, )

~/anaconda/lib/python3.6/site-packages/loompy/loompy.py in create(filename, matrix, row_attrs, col_attrs, file_attrs, chunks, chunk_cache, dtype, compression_opts)
   1019
   1020         if scipy.sparse.issparse(matrix):
-> 1021                 return _create_sparse(filename, matrix, row_attrs, col_attrs, file_attrs, chunks, chunk_cache, dtype, compression_opts)
   1022
   1023         # Create the file (empty).

~/anaconda/lib/python3.6/site-packages/loompy/loompy.py in _create_sparse(filename, matrix, row_attrs, col_attrs, file_attrs, chunks, chunk_cache, dtype, compression_opts)
    982                 if ds is None:
    983                         logging.info<http://logging.info>("Creating")
--> 984                         ds = create(filename, matrix[:, ix:ix + window].toarray(), row_attrs, ca, file_attrs, chunks, chunk_cache, dtype, compression_opts)
    985                 else:
    986                         logging.info<http://logging.info>("Adding columns")

~/anaconda/lib/python3.6/site-packages/loompy/loompy.py in create(filename, matrix, row_attrs, col_attrs, file_attrs, chunks, chunk_cache, dtype, compression_opts)
   1030
   1031         ds = connect(filename)
-> 1032         ds.set_layer("", matrix, chunks, chunk_cache, dtype, compression_opts)
   1033
   1034         for key, vals in row_attrs.items():

~/anaconda/lib/python3.6/site-packages/loompy/loompy.py in set_layer(self, name, matrix, chunks, chunk_cache, dtype, compression_opts)
    343                                 compression="gzip",
    344                                 shuffle=False,
--> 345                                 compression_opts=compression_opts
    346                         )
    347

~/anaconda/lib/python3.6/site-packages/h5py/_hl/group.py in create_dataset(self, name, shape, dtype, data, **kwds)
    103         """
    104         with phil:
--> 105             dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
    106             dset = dataset.Dataset(dsid)
    107             if name is not None:

~/anaconda/lib/python3.6/site-packages/h5py/_hl/dataset.py in make_new_dset(parent, shape, dtype, data, chunks, compression, shuffle, fletcher32, maxshape, compression_opts, fillvalue, scaleoffset, track_times)
     74     tmp_shape = maxshape if maxshape is not None else shape
     75     # Validate chunk shape
---> 76     if isinstance(chunks, tuple) and (-numpy.array([ i>=j for i,j in zip(tmp_shape,chunks) if i is not None])).any():
     77         errmsg = "Chunk shape must not be greater than data shape in any dimension. "\
     78                  "{} is not compatible with {}".format(chunks, shape)

TypeError: The numpy boolean negative, the `-` operator, is not supported, use the `~` operator or the logical_not function instead.


When I tried to make a minimal example, I got a different error however:

G = 10000
C = 100
S = sparse.eye(C, G).tocoo()

loompy.create('~/Desktop/test.loom', S,
              {'g_id': np.arange(G)},
              {'c_id': np.arange(C)}, )


Which gives

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-25-52cb84c445d9> in <module>()
      1 loompy.create('~/Desktop/test.loom', S,
      2               {'g_id': np.arange(G)},
----> 3               {'c_id': np.arange(C)}, )

~/anaconda/lib/python3.6/site-packages/loompy/loompy.py in create(filename, matrix, row_attrs, col_attrs, file_attrs, chunks, chunk_cache, dtype, compression_opts)
   1019
   1020         if scipy.sparse.issparse(matrix):
-> 1021                 return _create_sparse(filename, matrix, row_attrs, col_attrs, file_attrs, chunks, chunk_cache, dtype, compression_opts)
   1022
   1023         # Create the file (empty).

~/anaconda/lib/python3.6/site-packages/loompy/loompy.py in _create_sparse(filename, matrix, row_attrs, col_attrs, file_attrs, chunks, chunk_cache, dtype, compression_opts)
    982                 if ds is None:
    983                         logging.info<http://logging.info>("Creating")
--> 984                         ds = create(filename, matrix[:, ix:ix + window].toarray(), row_attrs, ca, file_attrs, chunks, chunk_cache, dtype, compression_opts)
    985                 else:
    986                         logging.info<http://logging.info>("Adding columns")

~/anaconda/lib/python3.6/site-packages/loompy/loompy.py in create(filename, matrix, row_attrs, col_attrs, file_attrs, chunks, chunk_cache, dtype, compression_opts)
   1022
   1023         # Create the file (empty).
-> 1024         f = h5py.File(name=filename, mode='w')
   1025         f.create_group('/layers')
   1026         f.create_group('/row_attrs')

~/anaconda/lib/python3.6/site-packages/h5py/_hl/files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, **kwds)
    270
    271                 fapl = make_fapl(driver, libver, **kwds)
--> 272                 fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
    273
    274                 if swmr_support:

~/anaconda/lib/python3.6/site-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
     96         fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
     97     elif mode == 'w':
---> 98         fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
     99     elif mode == 'a':
    100         # Open in append mode (read/write).

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/Users/ilan/minonda/conda-bld/h5py_1482533836832/work/h5py/_objects.c:2856)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/Users/ilan/minonda/conda-bld/h5py_1482533836832/work/h5py/_objects.c:2814)()

h5py/h5f.pyx in h5py.h5f.create (/Users/ilan/minonda/conda-bld/h5py_1482533836832/work/h5py/h5f.c:2269)()

OSError: Unable to create file (Unable to open file: name = '~/desktop/test.loom', errno = 2, error message = 'no such file or directory', flags = 13, o_flags = 602)

**Comment by slinnarsson** [comment]
Release 1.1.0 fixes this:

* Handle path names relative to home dir by calling `expanduser()` before h5py gets the path
* Handle sparse matrices of any dimension

Your example now works (flipping `G, C` in call to `eye`):

```python
G = 10000
C = 100
S = sparse.eye(G, C).tocoo()

loompy.create('~/Desktop/test.loom', S,
              {'g_id': np.arange(G)},
              {'c_id': np.arange(C)} )
```

I will push 1.1.0 to pypi once I've run some more extensive testing.

**Comment by arogozhnikov** [comment]
(I see it is an old discussion, but still)

> FYI, the opposite method is called sparse(). It returns a sparse matrix without loadibg the dense representation in memory.

When looking at implementation, I think it first reads whole file in numpy.array and then converts it to sparse matrix
https://github.com/linnarsson-lab/loompy/blob/2e620d2db8f203462dbd0ee8df08ed9fc6b8b0d7/loompy/loom_layer.py#L24

Indirectly it is confirmed by the fact I run out of memory when trying to open 20GB file using computer with 128GB.

**Comment by slinnarsson** [comment]
The line you're looking at is from MemoryLoomLayer, which is in memory anyway, so there's no other way to do it. For the normal LoomLayer, the sparse matrix is loaded incrementally without first loading the full dense matrix, although the way the loading works can probably be improved.
