### ISSUE TITLE
Loom file doubles in size for normalized Scanpy object vs. raw Scanpy object

### ISSUE THREAD

**Issue by twoneu** [linnarsson-lab/loompy#180]
Hello,

Thank you for this wonderful tool. I am using the following code to generate a loom file from my adata object created in Scanpy:

```
# create basic row and column attributes for the loom file:
row_attrs = {
    "Gene": np.array(adata.var_names) ,
}
col_attrs = {
    "CellID": np.array(adata.obs_names) ,
    "nGene": np.array( np.sum(adata.X.transpose()>0 , axis=0)).flatten() ,
    "nUMI": np.array( np.sum(adata.X.transpose() , axis=0)).flatten() ,
}
lp.create( f_loom_path_scenic_adata, adata.X.transpose(), row_attrs, col_attrs)
```
If adata.X is not log-normalized, the resulting loom file is about 500MB. However, if adata.X **is** log-normalized, the resulting loom file doubles to 1GB. I am very lost as to what could be causing this discrepancy - is this expected behavior, or are there ways to figure out what is causing the memory inflation?

**Comment by pl-ki** [comment]
If the raw data is integers, these might be stored as a smaller integer type, e.g. 'uint16', whereas the normalized values have to be floats, like 'float32' or 'float64'. Check the type of the data layer.
