### ISSUE TITLE
HDF5 Performance Tuning

### ISSUE THREAD

**Issue by JobLeonard** [linnarsson-lab/loompy#22]
Split out from #19 to avoid that topic from losing too much focus.

So I have spent some time in the past trying to tune the HDF5 settings of loompy (see [here](https://github.com/linnarsson-lab/loom-viewer/issues/90) and [here](https://github.com/JobLeonard/loompy-chunk-cache-experiments/blob/master/Loompy%20cache%20test.ipynb)), looking for the best trade-off in terms of compression size and disk access speed.

The very weird result so far is that regardless of the overrides I have tried for the chunk-cache, loading times remain the same, even if I set it to zero. I am on a maching with 64GB of RAM, I should be able to blow up the chunk cache to crazy numbers, and given the 64x64 chunk size see 64x less disk access. But nothing happens.

I'm thinking of opening a topic on the H5PY Google Groups to help me figure out what is wrong here, because the numbers make no sense. I guess that at the moment everything uses the default 1MB chunk cache, despite overrides. This is _ridiculously_ low on modern machines, and far from adequate for larger data sets (assuming 64x64 chunks and 32bit floats, you cannot even load a single row without evicting part of the chunk cache if you have more than ~6000 cells).

Another issue to discuss is the row- or column- major layout. This would focus on the low-level implementation question, the more "high level" discussion of the convention should remain in #19. HDF5 is neither, but loading data from HDF5 files through h5py will result in row-major Numpy arrays.

All of these questions also apply to connecting/creating loom files through R.

**Comment by slinnarsson** [comment]
In Loompy v2.0 the options to set chunk size and compression are removed. This is an implementation detail that should be hidden from the user. Current defaults seem to work well and until we come up with a compelling use case, we should stick with them.

As for row and column-major layout, surely loading the data from file takes way longer than transposing a matrix in memory. Thus it doesn't matter which way the data is stored, and the user can always transpose in RAM. Whether row- or column-major is desired will anyway differ depending on the use-case.

It's sad about the chunk cache though.  I tried the [h5py_cache](https://github.com/moble/h5py_cache) function but can confirm it made no difference in speed.
