### ISSUE TITLE
Python 3.5 import error

### ISSUE THREAD

**Issue by falexwolf** [linnarsson-lab/loompy#23]
Importing loompy under Python 3.6 works just fine, but Python 3.5 throws a syntax error
```
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:52:12) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import loompy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alexwolf/miniconda3/envs/py35/lib/python3.5/site-packages/loompy/__init__.py", line 2, in <module>
    from .loompy import connect, create, combine, create_from_cellranger, MemoryLoomLayer, LoomLayer, LoomView, LoomConnection
  File "/Users/alexwolf/miniconda3/envs/py35/lib/python3.5/site-packages/loompy/loompy.py", line 87
    data: np.ndarray = None
        ^
SyntaxError: invalid syntax
```

**Comment by slinnarsson** [comment]
Yes, we use [Python 3.6 syntax](https://docs.python.org/3/whatsnew/3.6.html). The error you get is for a [type-annotated variable](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep526), which was introduced in 3.6. We also use [formatted string literals](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep498), which also are 3.6-specific. 

In other words, loompy requires 3.6 to work properly.

**Comment by JobLeonard** [comment]
We should probably mention these requirements in [the installation documentation](http://loompy.org/loompy-docs/installation/index.html), and possibly also in the README.MD on GitHub, similar to how we do for velocyto and loom-viewer.

**Comment by falexwolf** [comment]
OK, Python 3.6 is very fine! And yes, you should! I was expecting something like this and looked through your docs but then didn't find any note about it. So I opened the issue. ;)
