### ISSUE TITLE
PyPi is still at version 1.1.0

### ISSUE THREAD

**Issue by JobLeonard** [linnarsson-lab/loompy#28]
https://pypi.python.org/pypi/loompy

**Comment by JobLeonard** [comment]
For the record, I only noticed this because the Python side of the `loom-viewer` needs to be updated to accommodate the breaking changes. I had not noticed this before, due to it relying on a version of loompy installed via pip. Which suggests that #28 needs to be resolved before I can migrate the loom-viewer to the improved loompy 2.0 API *and* deploy the migrated version to PyPi.

**Comment by slinnarsson** [comment]
Ooops. Fixed.

**Comment by slinnarsson** [comment]
@gioelelm this means that Travis CI does not submit to PyPi? Can we make it do so?

**Comment by JobLeonard** [comment]
Maybe Travis is just missing the required credentials to do so? I still have to turn on my old laptop to submit loom-viewer updates because I haven't copied them over to the new laptop yet :P

**Comment by gioelelm** [comment]
Did you tag the release (git tag) and push with tag?

**Comment by slinnarsson** [comment]
Yes (for 2.0): https://github.com/linnarsson-lab/loompy/tree/v2.0

But maybe 2.0 accidentally had version == 1.1.0 ?

**Comment by slinnarsson** [comment]
No, it was really 2.0

**Comment by gioelelm** [comment]
Next time you tag and push, check for possible error messages in travis.
Link: https://travis-ci.org/linnarsson-lab/loompy/builds

I checked old commits everything seem to have gone smoothly.

And @JobLeonard I think have the credentials correctly configured in travis

**Comment by gioelelm** [comment]
@JobLeonard or maybe you are right.... I found this error in the commit that should have deployed v2.0:

```
HTTPError: 403 Client Error: Invalid or non-existent authentication information. for url: https://upload.pypi.org/legacy/
```

But I don't understand why this is happening I am using the same credentials that I use for ``velocyto.py`` and there I have no problems!

**Comment by slinnarsson** [comment]
Ok I think there has been a [policy change at PyPi](https://packaging.python.org/tutorials/distributing-packages/#uploading-your-project-to-pypi). The old way of uploading builds is no longer supported and you need to do this:

1. Change your ~/.pypirc file as follows:

```
[distutils]
index-servers =
  pypi

[pypi]
username=slinnarsson
password=PASSWORD
```
(i.e. we're removing the legacy URL and the test server config)

2. Install Twine

```
pip install twine
```

3. Push a new release

First update the version in loompy/_version.py, then:

```
cd loompy
rm -r dist   (otherwise twine will upload the oldest build!)
python setup.py sdist
twine upload dist/*
```

@gioelelm could you make Travis CI use this new way?

**Comment by gioelelm** [comment]
I use a ["deploy"](https://github.com/linnarsson-lab/loompy/blob/master/.travis.yml#L47-L52) macro that travisCI provides.
Only thing that I do is writing in the password encrypted [here](https://github.com/linnarsson-lab/loompy/blob/master/.travis.yml#L50).  So there is nothing I can change I think. 

Did you find any issue? I can see that Travis has failed the build [here](https://travis-ci.org/linnarsson-lab/loompy/jobs/335100248)

**Comment by gioelelm** [comment]
And [velocyto.py travis script](https://github.com/linnarsson-lab/loompy/blob/master/.travis.yml) is doing exactly the same and is working without trouble se [here](https://travis-ci.org/velocyto-team/velocyto.py/builds/333348291). I don't understand where the bug is.

**Comment by slinnarsson** [comment]
Travis failed at uploading to PyPi. I uploaded manually instead. 

According to [this](http://www.dougalmatthews.com/2016/Sep/01/automate-publishing-to-pypi-with-pbr-and-travis/) Travis should use twine to upload, and the [log](https://travis-ci.org/linnarsson-lab/loompy/jobs/335100248) shows that it used https (i.e. with SSL, so Twine). But it still gets the 503 error. Maybe it was a temporary thing?

**Comment by slinnarsson** [comment]
I made a release "2.0.4" with tag "2.0.4" but Travis still fails and nothing got uploaded to PyPi.

**Comment by slinnarsson** [comment]
I guess I'll just remember to push manually to PyPi from now on, no big deal.

**Comment by gioelelm** [comment]
Apparently travisCI encypted passwords contain more info than just the password (e.g. the repo they were encrypted for) https://docs.travis-ci.com/user/deployment/pypi/

**Comment by gioelelm** [comment]
Ok officially solved! It works now!
