### ISSUE TITLE
Continuous testing

### ISSUE THREAD

**Issue by slinnarsson** [linnarsson-lab/loompy#36]
As we're getting more usage we need to provide better assurances that our releases are not going to break people's code. Thus we need continuous testing, via Travis CI.

**Comment by JobLeonard** [comment]
There's two built-in ways: unit testion and doc testing

https://docs.python.org/3/library/unittest.html

https://docs.python.org/3.5/library/doctest.html

I think the doc testing makes sense for checking if read-only works as expected, I'll see if adding it to the documentation makes Travis pick it up automagically. I guess that means we need to add a loom test file (creating a new one just to check would require adding that code to the doctest as well).

**Comment by slinnarsson** [comment]
We have the infrastructure for this now (with Travis CI), and I'll try to add progressively more tests.
