### ISSUE TITLE
Syntax error in setup.py 

### ISSUE THREAD

**Issue by Toseph** [linnarsson-lab/loompy#41]
Installing this on python-3.6.2, encountered a syntax issue in the setup.py file on line26:
	download_url=**f**"https://github.com/linnarsson-lab/loompy/archive/{__version__}.tar.gz",

The f should be removed to correct the error.

**Comment by slinnarsson** [comment]
Hi 

Are you sure you're on Python 3.6 ? That syntax is the new [string interpolation](https://www.python.org/dev/peps/pep-0498/) that was introduced in 3.6. The f is there to indicate that expressions inside curly braces should be expanded.

**Comment by JobLeonard** [comment]
In case you're not sure how to check: the most common cause for this would be having installed Anaconda, but having a different, older version of Python on the systems path.

**Comment by Toseph** [comment]
Hey all, this can be closed. 
I was able to get it running using a fresh installation of python3.6, there was an error with my virtualenv as it turned out and it was still referencing 2.7 system packages.
