### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by chartl** [linnarsson-lab/loompy#43]
It appears to not be possible to install loompy on py2 or py3:

> $ pip install -U loompy --user
> Collecting loompy
>   Using cached https://files.pythonhosted.org/packages/54/61/80632f11aa2185bb089ff3ddc14467389a92a0a369b3572cfa406bd6c32e/loompy-2.0.8.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/u/scratch/flashscratch1/c/chartl/pip-build-ukvz_ej5/loompy/setup.py", line 26
>         download_url=f"https://github.com/linnarsson-lab/loompy/archive/{__version__}.tar.gz",
>                                                                                             ^
>     SyntaxError: invalid syntax

Using the git source and altering the offending line to

> download_url=r"https://github.com/linnarsson-lab/loompy/archive/0.0.0.tar.gz"

still yields a bunch of (typing) syntax errors during installation [and this is with the typing package installed]

>   File "build/bdist.linux-x86_64/egg/loompy/attribute_manager.py", line 11
>     def __init__(self, ds: Any, *, axis: int) -> None:  # Note: can't give type for ds because it will be circular and mypy doesn't support it
>                          ^
> SyntaxError: invalid syntax
> 
> byte-compiling build/bdist.linux-x86_64/egg/loompy/file_attribute_manager.py to file_attribute_manager.pyc
>   File "build/bdist.linux-x86_64/egg/loompy/file_attribute_manager.py", line 9
>     def __init__(self, f: h5py.File) -> None:
>                         ^
> SyntaxError: invalid syntax
> 
> byte-compiling build/bdist.linux-x86_64/egg/loompy/graph_manager.py to graph_manager.pyc
>   File "build/bdist.linux-x86_64/egg/loompy/graph_manager.py", line 7
>     def _renumber(a: np.ndarray, keys: np.ndarray, values: np.ndarray) -> np.ndarray:
>                    ^
> SyntaxError: invalid syntax
> 
> byte-compiling build/bdist.linux-x86_64/egg/loompy/layer_manager.py to layer_manager.pyc
>   File "build/bdist.linux-x86_64/egg/loompy/layer_manager.py", line 11
>     def __init__(self, ds: Any) -> None:  # Note: can't give type for ds because it will be circular and mypy doesn't support it
>                          ^
> SyntaxError: invalid syntax
> 

(and for py3)

> byte-compiling build/bdist.linux-x86_64/egg/loompy/attribute_manager.py to attribute_manager.cpython-35.pyc
>   File "build/bdist.linux-x86_64/egg/loompy/attribute_manager.py", line 14
>     storage: Dict[str, np.ndarray] = {}
>            ^
> SyntaxError: invalid syntax
> 
> byte-compiling build/bdist.linux-x86_64/egg/loompy/file_attribute_manager.py to file_attribute_manager.cpython-35.pyc
>   File "build/bdist.linux-x86_64/egg/loompy/file_attribute_manager.py", line 11
>     storage: Dict[str, str] = {}
>            ^
> SyntaxError: invalid syntax
> 
> byte-compiling build/bdist.linux-x86_64/egg/loompy/graph_manager.py to graph_manager.cpython-35.pyc
>   File "build/bdist.linux-x86_64/egg/loompy/graph_manager.py", line 25
>     storage: Dict[str, np.ndarray] = {}
>            ^
> SyntaxError: invalid syntax
> 
> byte-compiling build/bdist.linux-x86_64/egg/loompy/layer_manager.py to layer_manager.cpython-35.pyc
>   File "build/bdist.linux-x86_64/egg/loompy/layer_manager.py", line 13
>     storage: Dict[str, np.ndarray] = {}
>

**Comment by slinnarsson** [comment]
Sorry, loompy requires Python 3.6, which supports string interpolation.
