### ISSUE TITLE
Suppress not relevant warning

### ISSUE THREAD

**Issue by gioelelm** [linnarsson-lab/loompy#52]
This warning get printed always when importing loompy (both in notebooks and stdout when running cmd line tools as velocyto).
If it is a problem of h5py and not ours, we should catch the warning so that it does not show up

```
/data/home/linnarsson/env/miniconda3/lib/python3.6/site-packages/h5py/__init__.py:36: 
FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
```

**Comment by slinnarsson** [comment]
I have never seen that warning. Which version of h5py are you using? I am on 2.7.0, but there is a later 2.7.1 as well. It [seems like](https://github.com/h5py/h5py/pull/926) the error is 2.7.1-specific, and has been fixed in 2.8.0rc1. Try it with:

```
pip install "h5py==2.8.0rc1"
```

**Comment by JobLeonard** [comment]
I have had the same warning for ages too. I guess that it currently happens when you install loompy from scratch (including a fresh Anaconda release), since it will pull 2.7.1

**Comment by slinnarsson** [comment]
Ok, I fixed it temporarily by suppressing warnings while importing h5py:

```python
import warnings
with warnings.catch_warnings():
	warnings.simplefilter("ignore")
	import h5py
```
