### ISSUE TITLE
Add get method to AttributeManager

### ISSUE THREAD

**Issue by astaric** [linnarsson-lab/loompy#53]
It should have the same signature and work in the same way as [dict's get method](https://docs.python.org/3/library/stdtypes.html#dict.get).

If it is something you would be willing to consider, let me know and I'll submit a PR with the change.

**Comment by slinnarsson** [comment]
Sure, sounds like a good idea. Please make the method check that the default value is a numpy array of the appropriate length and type (one of the loom allowed attribute types). I think it will help catch some errors.

**Comment by astaric** [comment]
I have opened a PR with the change (#54).

How would you suggest that the check for proper type should be made?
I would prefer to use and existing function for the check. One way I could think of would be to call normalize_attr_values with given default (discarding its return value). If it does not raise, the value could be considered valid.

**Comment by slinnarsson** [comment]
Thanks. Unfortunately, ensuring the proper types is very non-trivial. I think you should round-trip them like so: 

```python
return materialize_values(normalize_attr_values(default))
```

`normalize_attr_values` prepares values for being stored in HDF5, but it will turn unicode into HTML-entity-encoded ASCII. `materialize_values` does the reverse.

But please test with a few different kinds of attributes to make sure what I said makes sense. Especially various ways of supplying strings, e.g. numpy unicode array, numpy object array where the objects are unicode strings, regular python list of strings, ...
