### ISSUE TITLE
create_from_cellranger returns None

### ISSUE THREAD

**Issue by marcelm** [linnarsson-lab/loompy#55]
The [`create_from_cellranger()`](https://github.com/linnarsson-lab/loompy/blob/b91df787a57378f18a6269ae01985ab91d7a60a9/loompy/loompy.py#L890) function is documented to return a “LoomConnection to created loom file.”

It does not do this and actually returns only `None`. This is a problem as the caller first needs to infer the target file name in order to then `connect()` to it.

Possibly a better idea is to not return a connection, but the name of the created file. As the caller, I could then decide whether to `connect()` or not.

**Comment by slinnarsson** [comment]
Thanks, I implemented your suggestion in 2fdff96ea20a15f552e72a5d048422fb5dcdb7c7. Install latest commit from source to get it.

**Comment by marcelm** [comment]
That’s great, thanks a lot!
