### ISSUE TITLE
publicly available loom datasets?

### ISSUE THREAD

**Issue by jeff-regier** [linnarsson-lab/loompy#56]
Are there any scRNA-seq dataset in the loom format that are publicly available?  We just added loom support to [scVI](https://github.com/YosefLab/scVI) -- but we haven't tested in very thoroughly because we just have one loom dataset.

Thanks!

**Comment by slinnarsson** [comment]
http://loom.linnarssonlab.org !

**Comment by jeff-regier** [comment]
Great! We appreciate you sharing all those datasets.
