### ISSUE TITLE
always get error when use loompy.connect

### ISSUE THREAD

**Issue by wangmhan** [linnarsson-lab/loompy#58]
Hi,

First I run velocyto command like this, after get sorted .bam file: velocyto run_smartseq2 -o loomOutput -m mm10_ucsc_rmsk.gtf -e $dn3 $hisat2_bam $annotation
Then, I try to combine .loom files by loompy. First, I want to have a look at .loom files, so I run in python like this:
>>> import loompy
>>> ds=loompy.connect("EB.loom")
>>> ds
<loompy.loompy.LoomConnection object at 0x7fbd5a9492e8>
I cannot see the data matrix as you showed on :http://linnarssonlab.org/loompy/installation/index.html#
I also tried the example Cortex.loom, and get the same result.

**Comment by slinnarsson** [comment]
Are you running this in a [Jupyter notebook](http://jupyter.org)? 

If you are running in the terminal, you will get the output you show, because the terminal does not know how to display HTML formatted values.

**Comment by wangmhan** [comment]
Yes I am running in the terminal. Thank you. I will try Jupyter notebook
later.

2018-07-05 13:04 GMT+02:00 Sten Linnarsson <notifications@github.com>:
