### ISSUE TITLE
loompy.create with dict of sparse matrices

### ISSUE THREAD

**Issue by VolkerBergen** [linnarsson-lab/loompy#66]
`loompy.create` does not handle a `dict` of sparse matrices for `layers` as it raises

TypeError: ufunc 'isfinite' not supported for the input types

https://github.com/linnarsson-lab/loompy/blob/c171c4763c1e75420eb6cde071bf7892fd04d6fe/loompy/layer_manager.py#L100

**Comment by slinnarsson** [comment]
Yes, this is a known limitation. I will prioritize fixing it.

**Comment by slinnarsson** [comment]
Fixed by e11444f6ea7eac4f087b91bc6aafe2fe09e40ad2

**Comment by slinnarsson** [comment]
I made a new release, 2.0.12, which should be available at PyPi shortly. It fixes this issue and includes several other fixes and new features. Please let me know if this doesn't solve your problem.

**Comment by VolkerBergen** [comment]
Thanks, Sten!
