### ISSUE TITLE
Improve dependencies

### ISSUE THREAD

**Issue by flying-sheep** [linnarsson-lab/loompy#68]
If you don’t import `from .colors ...` in `__init__.py` then you can specify matplotlib as an optional dependency (`extras_require`)

Furthermore, `typing` is built into python, no need to depend on it.

**Comment by slinnarsson** [comment]
Thanks. I’ll update and make matplotlib optional.

**Comment by flying-sheep** [comment]
ok, i’ll do a quick PR
