### ISSUE TITLE
Decide on a default schema for attributes

### ISSUE THREAD

**Issue by JobLeonard** [linnarsson-lab/loompy#8]
@slinnarsson, @gioelelm 

@pl-ki asked me what the default metadata attributes are that we use in the Loom files. He wants to make sure that his changes to the pipeline have the right values come out by default.

This is probably a good moment decide if we want to support an officially suggested "attribute schema", one that we also put in the loom documentation. 

I'm in favour of this for the following reasons:

- while _we_ can see that a row attribute labelled `Gene`, `GENE` or `GeneName` is probably the same thing (labels for gene names), it's still a lot easier to write scripts that work on random `.loom` files if there are default conventions for common attributes.
- `loom-viewer` currently supports certain default values. Making these match default conventions makes the usage of the viewer easier: people know what to expect, I can make it do more things automatically.

The proposed updated schema below is based on three things

- metadata attributes added by `loompy.create_from_cellranger()`
- conventions used by `loom-viewer`
- the proposal in #7. Note: for `loom-viewer`, there is only one row attribute that is currently *required* for it to work: "Gene", this proposal would remove that need.

## Global Attributes

- `title` (optional, `loom-viewer` uses the file name if absent)
- `description` (optional)
- `url` (optional)
- `doi` (optional)

Suggested additions, as explained in #7: `rowName`, `rowKey`, `rowSearchKey`, `colName`, `colKey` and `colSearchKey`.

### Reserved global attribute

- `creation_date` 

Added by default when a `.loom` file is first created by loompy, used to sort loom files in viewer. It's good to be able to track when a loom file was first created, and we shouldn't mess with the attribute afterwards either.

## Column attributes

- `CellID` (optional, added by `create_from_cellranger`)

Default attribute for `colKey` and `colSearchKey`

###  Reserved column attributes (do not use)

- `(original order)` 

Used to keep track of original column order in `loom-viewer`.

## Row attributes

- `Accession` (optional, added by `create_from_cellranger`)
- `Gene` (optional, added by `create_from_cellranger`)

Default attributes for `rowKey` and `rowSearchKey`

###  Reserved row attributes (do not use)

- `(original order)` 

Used to keep track of original column order in `loom-viewer`.

# Supported default values

The `loom-viewer` will automatically check for the presence of certain row and column attributes, and use them as default values in various views. These are all optional attributes.

## Default x/y attribute for column scatterplot:

- `_X`, `_Y` (added by `create_from_cellranger`)
- `X`, `Y` (legacy support for older loom files, not suggested as schema)
- `SFDP_X`, `SFDP_Y`
- `_tSNE1`, `_tSNE2`
- `_PCA1`, `_PCA2`

## Default colour attribute for column scatterplot, heatmap, and sparkline:

- `Clusters` (created by `create_from_cellranger`)
- `Class`
- `Louvain_Jaccard`
- `_KMeans_10`

## Default x/y attribute for row scatterplot:

- `_X`, `_Y`
- `X`, `Y` (legacy support for older loom files, not suggested as schema)
- `_LogMean`, `_LogCV`
- `_tSNE1`, `_tSNE2`
- `_PCA1`, `_PCA2`

## Default color attribute for row scatterplot, heatmap, and sparkline:

- `_Selected`
- `_Excluded`

By the way, we also discussed adding default gene lists to `loompy` at one point, what happened to that?

Also, the documentation mentions this:

> The following global attributes are reserved:
>    schema, a type annotation schema (JSON-formatted string)

Didn't we ditch the schema requirement, since the Loom viewer [automatically infers data types](https://github.com/linnarsson-lab/loom-viewer/issues/77)?

- [ ] update documentation
  - [ ] global attributes: `colName`, `colKey`, `colSearchKey`, and `rowName`, `rowKey`, `rowSearchKey`
  - [ ] default values for the above: "Cells", `CellId`, `CellId`, and "Genes", `Accession`, `Gene`
  - [ ] reserved list: `(original order)`
  - [ ] Default values
    - [ ] default x/y attributes
    - [ ] default colour attributes
  - [ ] remove `schema` from reserved list?

**Comment by slinnarsson** [comment]
I agree, this is a good idea. The ones that are used by the cytograph pipeline are:

### Column attributes

`Clusters` (the cluster ID, int label from 0 to n_clusters)
`CellID` (string; not really used, but assumed to be present)
`_X` and `_Y` (float; I regret the underscores, but probably too late to change now)
`_Valid` (0 or 1, indicating valid cells)

### Row attributes

`Gene` (string human-readable, not unique)
`Accession` (string, computer-readable, unique)
`_Selected` (1 or 0)
`_Excluded` (1 or 0)

--
 We did indeed remove the schema requirement, so this should be removed from docs.

**Comment by JobLeonard** [comment]
Regarding the underscores: as far as the `loom-viewer` is concerned this is not an issue, since it uses a list of potential default attributes, and supporting plain `X` and `Y` is as simple as putting them higher in the list.

I don't know about other code you are using of course, but here is the equivalent Python code:

```python

def firstMatch(keys, searchkeys):
	for key in searchkeys:
		try:
			keys.index(key)
			return key
		except:
			# not present, try next key
			continue
	return None

def firstPair(keys, pairs):
	for pair in pairs:
		x, y = pair
		try:
			keys.index(x)
			keys.index(y)
			return pair
		except:
			# one of the keys not present, try next tuple
			continue
	return None
```

test:
```python
>> pairs = [('X', 'Y'), ('A', 'B')]
>> keys = ['A', 'X',  'C', 'B',  'D', 'Y'] # list of dictionary keys, order unimportant
>> firstPair(keys, pairs)
     ('X', 'Y')
>> firstPair(keys, [('B', 'C')])
     ('B', 'C')
```

You could use it as:

```python
# First matching X/Y attribute, backwards compatible with older loom files
firstPair(ds.col_attrs.keys(), [('X', 'Y'), ('_X', '_Y'), ('SFDP_X', 'SFDP_Y'), ('_tSNE1', '_tSNE2'), ('_PCA1', '_PCA2')]
```
Maybe that would make it easier to make your scripts backwards-compatible?

**Comment by slinnarsson** [comment]
To clarify: the attributes I mentioned above are and should be standard for **cytograph**, not for Loom or loompy. Loom should not presume that the file contains cells, genes or clusters.

The rowKey etc attributes should be standard for the **loom-viewer** only, not Loom or loompy. And they should not be camelCase, but python-style: `row_key` etc.

**Comment by slinnarsson** [comment]
Closing this and opening a new issue to invite developers of other pipelines to discuss.
