### ISSUE TITLE
Issue with layer.sparse() when accessing particular columns

### ISSUE THREAD

**Issue by ejarmand** [linnarsson-lab/loompy#82]
I was recently working with the sparse function and realized it would always fail when trying to access fewer than all columns because of some indexing issues. Thankfully @wayneidoyle came up with a solution. 

``def sparse(self, rows: np.ndarray = None, cols: np.ndarray = None) -> scipy.sparse.coo_matrix:
		n_genes = self.ds.shape[0] if rows is None else rows.shape[0]
		n_cells = self.ds.shape[1] if cols is None else cols.shape[0]

		data: List[np.ndarray] = []
		row: List[np.ndarray] = []
		col: List[np.ndarray] = []
		i = 0
		for (ix, selection, view) in self.ds.scan(items=cols, axis=1, layers=[self.name]):
			if rows is not None:
				vals = view.layers[self.name][rows, :]
			else:
				vals = view.layers[self.name][:, :]
			nonzeros = np.where(vals > 0)
			data.append(vals[nonzeros])
			row.append(nonzeros[0])
			col.append(nonzeros[1] + i)
			i += selection.shape[0]            
		return scipy.sparse.coo_matrix((np.concatenate(data), (np.concatenate(row),
np.concatenate(col))), shape=(n_genes, n_cells)``

**Comment by slinnarsson** [comment]
Hi & thanks. Would you mind making a pull request? Will make it a bit easier to test and integrate.
