### ISSUE TITLE
create_from_cellranger() incompatible w/ Cellranger 3.0

### ISSUE THREAD

**Issue by glrs** [linnarsson-lab/loompy#84]
Having installed CellRanger 3.0 (v3.0.1), I tried to generate loom files using create_from_cellranger() (loompy v2.0.16). I got the following:

```
File "/home/user/virtualenv-15.2.0/pyEnv2/lib/python3.6/site-packages/loompy/loompy.py", line 1025, in create_from_cellranger
    genome = [f for f in os.listdir(matrix_folder) if not f.startswith(".")][0]
FileNotFoundError: [Errno 2] No such file or directory: '/data/user/chromium/samples/10X_069/outs/filtered_gene_bc_matrices'
```

According to the release notes of CellRanger 3.0, there are some changes in the output file format (quoting some points bellow):

> **Output File Format Changes**
> - The file formats of the gene-barcode matrix (now called the feature-barcode matrix) have changed to accomodate Feature Barcoding results.
> - The mtx and barcodes.tsv files are now gzipped to save disk space
> - The genes.tsv file has been renamed features.tsv.gz, and contains extra columns indicating the feature_type of each gene / feature.

https://support.10xgenomics.com/single-cell-gene-expression/software/release-notes/3-0

**Comment by slinnarsson** [comment]
Might be something that @pl-ki has fixed already? I think you ran some V3 datasets and made loom files, right?

**Comment by pl-ki** [comment]
Right, I forgot to push this, will do shortly!

**Comment by glrs** [comment]
@slinnarsson we will start with V3 in January. This one was still V2, but it's clear now with @pl-ki 's reply. Thanks :)

**Comment by marcelm** [comment]
I was just having the same problem. Using current master solves the problem for me, but it would also be great if a new released could be tagged!

**Comment by slinnarsson** [comment]
I pushed `2.0.17` just now and it should be in pypi shortly.

Note: conda loompy is not updated, so please use `pip install -U loompy` to update

**Comment by marcelm** [comment]
Thanks a lot!
