### ISSUE TITLE
Trouble starting with loomR

### ISSUE THREAD

**Issue by juliesawitzke** [linnarsson-lab/loompy#88]
I'm a beginner and just learning about single cell datasets. I was told I should take a tutorial in LoomR, and I'm already stuck. I downloaded R, downloaded all the dependencies (R6, hdf5r, iterators, itertools, and C++API). I think they downloaded anyway - lots of red scripts scrolling by that are solid jargon that I don't understand). After all that I typed install.packages ("loomR") and got this: 
Warning message: package 'loomR' is not available (for R version 3.5.2)
Any ideas on how to proceed?
I am on a mac version 10.14.2 Mojave.

**Comment by slinnarsson** [comment]
Hi

Sorry for your troubles. For help with R and loomR, please go to: https://github.com/mojaveazure/loomR
