### ISSUE TITLE
Global attributes of type float64?

### ISSUE THREAD

**Issue by pl-ki** [linnarsson-lab/loompy#9]
Seems that global attributes can only be string. Is this on purpose? I think we could allow also float64 like row/col attrs.

**Comment by slinnarsson** [comment]
Yes, sure.

-- 
Sten Linnarsson, PhD
Professor of Molecular Systems Biology
Karolinska Institutet 
Unit of Molecular Neurobiology 
Department of Medical Biochemistry and Biophysics 
Scheeles väg 1, 171 77 Stockholm, Sweden
+46 8 52 48 75 77 (office)
+46 70 399 32 06 (mobile)

**Comment by pl-ki** [comment]
Only 'str' attributes are utf8-encoded at storing, others unencoded. All 'bytes' attributes are utf8-decoded when retrieved.
