### ISSUE TITLE
Validate should open h5py read-only

### ISSUE THREAD

**Issue by thouis** [linnarsson-lab/loompy#91]
This line prevents loom files to be opened read-only if another process has them open for 'r+', even if the mode in connect() is set to 'r'.  Validation should probably be a read-only operation.

https://github.com/linnarsson-lab/loompy/blob/e800b5dde59e276d5b451eb7b311997b60d29a58/loompy/loom_validator.py#L48

**Comment by thouis** [comment]
passing validate=False to connect() gets around this, but that argument seems like it should be orthogonal to r/w issues.

**Comment by slinnarsson** [comment]
Yes, good point. I will make the fix.

**Comment by slinnarsson** [comment]
Fixed by b40a2ef195e2b7273a4c8bc7a4ca18b1542816f2
