### ISSUE TITLE
Spec on graph index

### ISSUE THREAD

**Issue by nh3** [linnarsson-lab/loompy#92]
Currently there's no description on whether the vertex index (`a` and `b`) in col_graphs, row_graphs should be 0-based or 1-based. R uses 1-based index and certain loom reader (bioconductor/LoomExperiment) errs on 0-based index. It would be good to explicitly state this in format spec.

**Comment by slinnarsson** [comment]
Good point. I will fix. [Obviously](http://www.cs.utexas.edu/users/EWD/transcriptions/EWD08xx/EWD831.html), indexing should be zero-based.

**Comment by slinnarsson** [comment]
Fixed by 4cb23980a5d5f4e872b127702a71d6758a495778
