### ISSUE TITLE
Loom viewer on mousebrain.org

### ISSUE THREAD

**Issue by juliesawitzke** [linnarsson-lab/loompy#94]
Hi, I haven't been able to connect to the loom viewer on mousebrain.org for almost a week. Is this site permanently down? I've attached a screenshot of the error I am getting:
![Screenshot 2019-03-18 at 19 47 40](https://user-images.githubusercontent.com/44974172/54555325-c5a04000-49b6-11e9-862f-04328e4b043e.png)

**Comment by slinnarsson** [comment]
@pl-ki Can you look at this? Probably just needs a restart but I don't remember exactly how to do it.

**Comment by pl-ki** [comment]
should work now.
