### ISSUE TITLE
loompy combine() got multiple values for argument 'key'

### ISSUE THREAD

**Issue by IrinnaP** [linnarsson-lab/loompy#95]
Hello, apologies if this is a very simple thing, but I'm having a lot of trouble combining two loom  files:

combined = loompy.combine('/Users/ip97/sample8047HRTGFP_unpacked.loom', '/Users/ip97/sample8115HRTGFP_unpacked.loom','combined.loom', key='Accession')

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-39-716b178e20e5> in <module>
----> 1 combined = loompy.combine('sample8047HRTGFP_unpacked.loom', 'sample8115HRTGFP_unpacked.loom','combined.loom', key='Accession')

TypeError: combine() got multiple values for argument 'key'

I've tried using a different row attribute but it didn't seem to make a difference - here are all the row attributes: ['Accession', 'Chromosome', 'End', 'Gene', 'Start', 'Strand']

Any suggestion would be greatly appreciated!

**Comment by slinnarsson** [comment]
Hi

The loom files you want to combine must be provided as a list or tuple! 

```python
combined = loompy.combine(['sample8047HRTGFP_unpacked.loom', 'sample8115HRTGFP_unpacked.loom'], 'combined.loom', key='Accession')
```

(the way you did it, `combined.loom` is the third argument, which is the `key` argument, hence Python complains that you provided the `key` argument twice)

**Comment by IrinnaP** [comment]
Ahh thanks so much!
