### ISSUE TITLE
`LoomConnection.pandas` function returns `n_cells` copies of the same row

### ISSUE THREAD

**Issue by scottgigante** [linnarsson-lab/loompy#96]
The `pandas` method seems to be returning a dataframe full of identical rows.
```
>>> with loompy.connect(filename="file.loom") as loom:
>>>     df = loom.pandas("Gene").set_index("CellID")
>>> 
>>> for col in ['Clusters', '_X', '_Y']:
>>>     del df[col]
>>> mat = df.values
>>> np.all(mat == mat[0])
True
>>> with loompy.connect(filename="file.loom") as loom:
>>>     df = pd.SparseDataFrame(loom.layers['spliced'].sparse().T, default_fill_value=0.0)
>>> df.index=loom.ca['CellID']
>>> df.columns=loom.ra['Gene']
>>> mat = df.to_dense().values
>>> np.all(mat == mat[0])
False
```
loompy: 2.0.17
pandas: 0.23.4
scipy: 1.2.1
numpy: 1.15.0
python: 3.7.1

**Comment by slinnarsson** [comment]
Hi

Sorry about that. I don't really have time to troubleshoot, as we don't use pandas much. If you come up with a fix, please send a pull request (or just send me the fix by email). In the meantime, I've removed the method so as not to cause bugs for people. I also think the API of that method could use some more thought by someone who know more about idiomatic pandas than I do.
